name: Docker Image CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: div-c-web

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag harbor.divsphere.net/rose/div-c_web:latest

    - name: Login into harbor.divsphere.net
      run: echo ${{ secret.HARBOR_PASSWORD }} | docker login -u  ${{secret.HARBOR_PASSWORD }} ---password-stdin harbor.divsphere.net

    - name: push image
      run: docker push harbor.divsphere.net/rose/div-c_web:latest
