name: Docker Image CI

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: create .env
      run: |
        echo {{ secrets.ENDPOINT_ENV }} > .env
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag harbor.divsphere.net/rose/div-c_web:latest

    - name: Login into harbor.divsphere.net
      run: echo ${{ secrets.HARBOR_PASSWORD }} | docker login -u  ${{secrets.HARBOR_USERNAME }} --password-stdin harbor.divsphere.net

    - name: push image
      run: docker push harbor.divsphere.net/rose/div-c_web:latest
